# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      minor-and-patch-github-actions:
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directory: iac
    schedule:
      interval: daily
    groups:
      minor-and-patch-github-actions:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: backend
    schedule:
      interval: daily
    groups:
      minor-and-patch-python:
        update-types:
          - minor
          - patch
