# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-and-patch-github-actions:
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directory: iac
    schedule:
      interval: weekly
    groups:
      minor-and-patch-terraform:
        update-types:
          - minor
          - patch

  - package-ecosystem: uv
    directory: backend
    schedule:
      interval: weekly
    groups:
      minor-and-patch-python:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: ui
    schedule:
      interval: weekly
    groups:
      minor-and-patch-npm:
        update-types:
          - minor
          - patch
