name: Build


on:
  workflow_call:


permissions:
  contents: read
  pull-requests: write


jobs:

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ./backend/.python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: ./backend/uv.lock

      - working-directory: ./backend/
        run: uv run build.py


  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ./ui/package.json
          cache: npm
          cache-dependency-path: ./ui/package-lock.json

      - working-directory: ./ui/
        run: npm ci

      - working-directory: ./ui/
        run: npm run build
