name: Continuous Integration


on:
  pull_request:
    branches:
      - main


jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Python lint check
        working-directory: ./src/
        run: uvx ruff check

      - name: Python format check
        working-directory: ./src/
        run: uvx ruff format --check
